version: 2

sources:
  - name: public
    database: stock_pipeline
    schema: public
    tables:
      - name: stock_prices
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: ticker
            tests:
              - not_null
              - accepted_values:
                  values: ['AAPL', 'GOOGL', 'MSFT', 'AMZN']
          - name: close_price
            tests:
              - not_null
          - name: trade_date
            tests:
              - not_null